Repository GDGoC-SucceSS-Team15/Parker_Backend, pull requests merged in 2025-01, with the labels that each got.

#3 [#3 FEAT] 도메인 생성
  .github/PULL_REQUEST_TEMPLATE.yml
  .idea/gradle.xml
  .idea/misc.xml
  .idea/uiDesigner.xml
  parker/src/main/java/com/si9nal/parker/bookmark/domain/SpaceBookmark.java
  parker/src/main/java/com/si9nal/parker/bookmark/domain/ViolationBookmark.java
  parker/src/main/java/com/si9nal/parker/global/common/BaseEntity.java
  parker/src/main/java/com/si9nal/parker/parkingspace/domain/ParkingSpace.java
  parker/src/main/java/com/si9nal/parker/parkingspace/domain/enums/FeeType.java
  parker/src/main/java/com/si9nal/parker/parkingspace/domain/enums/ParkingType.java
  parker/src/main/java/com/si9nal/parker/parkingspace/domain/enums/ParkingUsage.java
  parker/src/main/java/com/si9nal/parker/parkingvioation/domain/ParkingViolation.java
  parker/src/main/java/com/si9nal/parker/report/domain/Report.java
  parker/src/main/java/com/si9nal/parker/report/domain/enums/ApprovalStatus.java
  parker/src/main/java/com/si9nal/parker/user/User.java
  parker/src/main/java/com/si9nal/parker/user/enums/Status.java
Labels: ✨ Feature, 🐞 BugFix, 👩‍💻 승은

#7 [Chore] PR템플릿 형식 변경
  .github/PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.yml
Labels: 👩‍💻 세은, ⚙ Setting

#6 [#4 FEAT] 인증 기능 구현 (회원가입, 로그인, 로그아웃, 회원탈퇴)
  .idea/dataSources.xml
  .idea/modules.xml
  .idea/modules/parker.main.iml
  parker/build.gradle
  parker/src/main/java/com/si9nal/parker/ParkerApplication.java
  parker/src/main/java/com/si9nal/parker/bookmark/domain/SpaceBookmark.java
  parker/src/main/java/com/si9nal/parker/bookmark/domain/ViolationBookmark.java
  parker/src/main/java/com/si9nal/parker/global/common/config/WebSecurityConfig.java
  parker/src/main/java/com/si9nal/parker/global/common/security/JwtFilter.java
  parker/src/main/java/com/si9nal/parker/global/common/security/TokenProvider.java
  parker/src/main/java/com/si9nal/parker/report/domain/Report.java
  parker/src/main/java/com/si9nal/parker/user/controller/UserController.java
  parker/src/main/java/com/si9nal/parker/user/domain/User.java
  parker/src/main/java/com/si9nal/parker/user/domain/enums/Status.java
  parker/src/main/java/com/si9nal/parker/user/dto/req/UserLoginReqDto.java
  parker/src/main/java/com/si9nal/parker/user/dto/req/UserSignupReqDto.java
  parker/src/main/java/com/si9nal/parker/user/dto/res/TokenDto.java
  parker/src/main/java/com/si9nal/parker/user/dto/res/UserInfoResDto.java
  parker/src/main/java/com/si9nal/parker/user/enums/Status.java
  parker/src/main/java/com/si9nal/parker/user/repository/UserRepository.java
  parker/src/main/java/com/si9nal/parker/user/service/UserService.java
  parker/src/main/resources/application.properties
  parker/src/main/resources/application.yml
Labels: ✨ Feature, 📬 API, 🔒 Security, 📦 Dependency, 👩‍💻 세은
