Repository GDGoC-SucceSS-Team15/Parker_Backend, pull requests merged in 2025-02, with the labels that each got.

#12 [#8 FEAT] 현재 위치 기반 주차공간 위치 조회
  .idea/dataSources.xml
  parker/build.gradle
  parker/src/main/java/com/si9nal/parker/global/common/util/Direction.java
  parker/src/main/java/com/si9nal/parker/global/common/util/GeometryUtil.java
  parker/src/main/java/com/si9nal/parker/global/common/util/Location.java
  parker/src/main/java/com/si9nal/parker/parkingspace/controller/ParkingSpaceController.java
  parker/src/main/java/com/si9nal/parker/parkingspace/domain/ParkingSpace.java
  parker/src/main/java/com/si9nal/parker/parkingspace/dto/res/ParkingSpaceMapDto.java
  parker/src/main/java/com/si9nal/parker/parkingspace/repository/ParkingSpaceRepository.java
  parker/src/main/java/com/si9nal/parker/parkingspace/service/ParkingSpaceService.java
  parker/src/main/resources/application.yml
  parker/src/test/java/com/si9nal/parker/parkingspace/controller/ParkingSpaceControllerTest.java
  parker/src/test/java/com/si9nal/parker/parkingspace/fixture/TestFixture.java
  parker/src/test/java/com/si9nal/parker/parkingspace/repository/ParkingSpaceRepositoryTest.java
  parker/src/test/java/com/si9nal/parker/parkingspace/service/ParkingSpaceServiceTest.java
  parker/src/test/resources/application.yml
Labels: ✨ Feature, 📬 API, ✅ Test, 📦 Dependency, 👩‍💻 승은

#15 [#14 Feat] 불법 주정차 단속 위치 정보 상세 조회 기능 개선
  parker/src/main/java/com/si9nal/parker/parkingvioation/controller/ParkingViolationDetailController.java
  parker/src/main/java/com/si9nal/parker/parkingvioation/domain/ParkingViolation.java
  parker/src/main/java/com/si9nal/parker/parkingvioation/dto/res/ParkingViolationDetailResponseDto.java
  parker/src/main/java/com/si9nal/parker/parkingvioation/repository/ParkingViolationRepository.java
  parker/src/main/java/com/si9nal/parker/parkingvioation/service/ParkingViolationDetailService.java
Labels: ✨ Feature, 📬 API, 👩‍💻 세은

#16 [#13 Feat] Swagger 설정
  parker/build.gradle
  parker/src/main/java/com/si9nal/parker/global/common/config/SwaggerConfig.java
  parker/src/main/java/com/si9nal/parker/global/common/config/WebSecurityConfig.java
  parker/src/main/resources/application.yml
Labels: ✨ Feature, 👩‍💻 승은, ⚙ Setting

#18 [#11 FEAT] 사용자 위치 중심으로 주차공간 및 단속 위치 조회
  parker/build.gradle
  parker/src/main/java/com/si9nal/parker/camera/domain/CameraLocation.java
  parker/src/main/java/com/si9nal/parker/camera/repository/CameraLocationRepository.java
  parker/src/main/java/com/si9nal/parker/global/common/config/WebSecurityConfig.java
  parker/src/main/java/com/si9nal/parker/map/controller/MapMainController.java
  parker/src/main/java/com/si9nal/parker/map/dto/response/CameraLocationResponse.java
  parker/src/main/java/com/si9nal/parker/map/dto/response/Location.java
  parker/src/main/java/com/si9nal/parker/map/dto/response/ParkingSpaceResponse.java
  parker/src/main/java/com/si9nal/parker/map/dto/response/ParkingViolationResponse.java
  parker/src/main/java/com/si9nal/parker/map/service/MapMainService.java
  parker/src/main/java/com/si9nal/parker/map/util/GeometryUtil.java
  parker/src/main/java/com/si9nal/parker/parkingspace/domain/ParkingSpace.java
  parker/src/main/java/com/si9nal/parker/parkingspace/repository/ParkingSpaceRepository.java
  parker/src/main/java/com/si9nal/parker/parkingvioation/repository/ParkingViolationRepository.java
Labels: ✨ Feature, 📬 API, 📦 Dependency, 👩‍💻 지원

#19 [Refactor] 이슈 템플릿 수정
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/deploy_request.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/ISSUE_TEMPLATE/refactor_request.yml
Labels: 🔨 Refactor, 🐞 BugFix, 👩‍💻 승은

#22 [#21 Refactor] API 응답 구조 통일
  .idea/compiler.xml
  parker/src/main/java/com/si9nal/parker/global/common/apiPayload/ApiResponse.java
  parker/src/main/java/com/si9nal/parker/global/common/apiPayload/code/BaseCode.java
  parker/src/main/java/com/si9nal/parker/global/common/apiPayload/code/BaseErrorCode.java
  parker/src/main/java/com/si9nal/parker/global/common/apiPayload/code/ErrorReasonDTO.java
  parker/src/main/java/com/si9nal/parker/global/common/apiPayload/code/ReasonDTO.java
  parker/src/main/java/com/si9nal/parker/global/common/apiPayload/code/status/ErrorStatus.java
  parker/src/main/java/com/si9nal/parker/global/common/apiPayload/code/status/SuccessStatus.java
  parker/src/main/java/com/si9nal/parker/global/common/apiPayload/exception/ExceptionAdvice.java
  parker/src/main/java/com/si9nal/parker/global/common/apiPayload/exception/GeneralException.java
  parker/src/main/java/com/si9nal/parker/parkingspace/controller/ParkingSpaceController.java
  parker/src/main/java/com/si9nal/parker/parkingspace/service/ParkingSpaceService.java
  parker/src/main/resources/application.yml
  parker/src/test/java/com/si9nal/parker/parkingspace/controller/ParkingSpaceControllerTest.java
  parker/src/test/java/com/si9nal/parker/parkingspace/service/ParkingSpaceServiceTest.java
Labels: ✨ Feature, 🔨 Refactor, ✅ Test, 👩‍💻 승은

#27 [#25 Feat] 불법주정차 단속 구역 신고
  parker/build.gradle
  parker/src/main/java/com/si9nal/parker/global/common/config/AmazonConfig.java
  parker/src/main/java/com/si9nal/parker/global/common/s3/AmazonS3Manager.java
  parker/src/main/java/com/si9nal/parker/global/common/s3/Uuid.java
  parker/src/main/java/com/si9nal/parker/global/common/s3/UuidRepository.java
  parker/src/main/java/com/si9nal/parker/report/controller/ReportController.java
  parker/src/main/java/com/si9nal/parker/report/domain/Report.java
  parker/src/main/java/com/si9nal/parker/report/dto/req/ReportPostRequestDto.java
  parker/src/main/java/com/si9nal/parker/report/dto/res/ReportPostResponseDto.java
  parker/src/main/java/com/si9nal/parker/report/repository/ReportRepository.java
  parker/src/main/java/com/si9nal/parker/report/service/ReportPostService.java
  parker/src/main/java/com/si9nal/parker/user/repository/UserRepository.java
  parker/src/main/resources/application.yml
Labels: ✨ Feature, 📬 API, 👩‍💻 승은

#28 [#20 Feat] 주차 공간 조회 기능
  parker/src/main/java/com/si9nal/parker/bookmark/repository/SpaceBookmarkRepository.java
  parker/src/main/java/com/si9nal/parker/global/common/apiPayload/exception/ExceptionAdvice.java
  parker/src/main/java/com/si9nal/parker/global/common/config/WebSecurityConfig.java
  parker/src/main/java/com/si9nal/parker/map/controller/MapMainController.java
  parker/src/main/java/com/si9nal/parker/map/dto/response/ParkingSpaceDetailResponse.java
  parker/src/main/java/com/si9nal/parker/map/dto/response/ParkingSpaceNearbyResponse.java
  parker/src/main/java/com/si9nal/parker/map/dto/response/ParkingSpaceNearbyResponseList.java
  parker/src/main/java/com/si9nal/parker/map/dto/response/ParkingSpaceSimpleResponse.java
  parker/src/main/java/com/si9nal/parker/map/dto/response/ParkingSpaceSummaryResponse.java
  parker/src/main/java/com/si9nal/parker/map/dto/response/ParkingViolationResponse.java
  parker/src/main/java/com/si9nal/parker/map/dto/response/ParkingViolationSimpleResponse.java
  parker/src/main/java/com/si9nal/parker/map/service/MapMainService.java
  parker/src/main/java/com/si9nal/parker/map/util/GeometryUtil.java
Labels: ✨ Feature, 📬 API, 👩‍💻 지원

#39 [#34 Feat] 위치 즐겨찾기 추가 및 삭제
  parker/src/main/java/com/si9nal/parker/bookmark/controller/BookmarkController.java
  parker/src/main/java/com/si9nal/parker/bookmark/domain/SpaceBookmark.java
  parker/src/main/java/com/si9nal/parker/bookmark/domain/ViolationBookmark.java
  parker/src/main/java/com/si9nal/parker/bookmark/dto/res/SpaceBookmarkResDto.java
  parker/src/main/java/com/si9nal/parker/bookmark/dto/res/ViolationBookmarkResDto.java
  parker/src/main/java/com/si9nal/parker/bookmark/repository/SpaceBookmarkRepository.java
  parker/src/main/java/com/si9nal/parker/bookmark/repository/ViolationBookmarkRepository.java
  parker/src/main/java/com/si9nal/parker/bookmark/service/BookmarkService.java
Labels: ✨ Feature, 📬 API, 👩‍💻 이나

#40 [#29 Refactor] DTO 문자열 처리 로직 유틸클래스로 분리 및 GeometryUtil 클래스 통일
  parker/src/main/java/com/si9nal/parker/global/common/util/DtoFormatUtil.java
  parker/src/main/java/com/si9nal/parker/global/common/util/GeometryUtil.java
  parker/src/main/java/com/si9nal/parker/map/dto/response/Location.java
  parker/src/main/java/com/si9nal/parker/map/dto/response/ParkingSpaceDetailResponse.java
  parker/src/main/java/com/si9nal/parker/map/dto/response/ParkingSpaceNearbyResponse.java
  parker/src/main/java/com/si9nal/parker/map/dto/response/ParkingSpaceSummaryResponse.java
  parker/src/main/java/com/si9nal/parker/map/service/MapMainService.java
  parker/src/main/java/com/si9nal/parker/map/util/GeometryUtil.java
Labels: 🔨 Refactor, 🎨 Style, 👩‍💻 지원

#44 [#41 Feat] 주차 구역 즐겨찾기 조회 및 정렬
  parker/src/main/java/com/si9nal/parker/bookmark/controller/BookmarkController.java
  parker/src/main/java/com/si9nal/parker/bookmark/repository/SpaceBookmarkRepository.java
  parker/src/main/java/com/si9nal/parker/bookmark/service/BookmarkListService.java
Labels: ✨ Feature, 📬 API, 👩‍💻 이나

#46 [#45 Refactor] 즐겨찾기 응답구조 통일, 에러처리, swagger 적용
  parker/src/main/java/com/si9nal/parker/bookmark/controller/BookmarkController.java
  parker/src/main/java/com/si9nal/parker/bookmark/repository/SpaceBookmarkRepository.java
  parker/src/main/java/com/si9nal/parker/bookmark/service/BookmarkListService.java
  parker/src/main/java/com/si9nal/parker/bookmark/service/BookmarkService.java
Labels: 📃 Docs, 🔨 Refactor, 👩‍💻 이나, 🎨 Style
